# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-30 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celebrateme_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='deceased_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='celebrateme_app.Deceased'),
        ),
        migrations.AlterField(
            model_name='image',
            name='deceased_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='celebrateme_app.Deceased'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='deceased_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='celebrateme_app.Deceased'),
        ),
    ]
